version: '3.9'
services:
  db:
    container_name: db
    image: "postgres:13-alpine"
    restart: "always"
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./docker/server.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expense-jar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on: [ "db" ]
  # flyway:
  #   image: "flyway/flyway:9.8.1-alpine"
volumes:
  postgres:
    # client:
    #   build: .
    #   ports:
    #     - "3000:3000"
