version: '3.9'
services:
  db:
    image: "postgres:13-alpine"
    restart: "always"
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build:
      context: ./
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - .:/app
    depends_on: [ "db" ]
volumes:
  postgres:
    # client:
    #   build: .
    #   ports:
    #     - "3000:3000"
