version: '3.9'
services:
  db:
    container_name: db
    image: "postgres:13-alpine"
    restart: "always"
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./docker/server.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expense-jar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - .:/app
    depends_on: [ "db" ]
volumes:
  postgres:
    # client:
    #   build: .
    #   ports:
    #     - "3000:3000"
